### ISSUE TITLE
Cannot start application ( Chrome failed during startup .....)

### ISSUE THREAD

**Issue by anhducanh14** [kuoruan/Chromium-Android#40]
When i cloned and install app. cannot start app. Maybe something wrong with lib or missing somthing.

**Comment by kuoruan** [comment]
Need more information. Could you please paste your logcat here?

**Comment by anhducanh14** [comment]
E/cr_VariationsSeedFetch: IOException when fetching variations seed.
    java.io.InterruptedIOException
        at com.android.okio.Deadline.throwIfReached(Deadline.java:56)
        at com.android.okio.Okio$1.write(Okio.java:67)
        at com.android.okio.RealBufferedSink.flush(RealBufferedSink.java:154)
        at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:126)
        at com.android.okhttp.internal.http.HttpTransport.flushRequest(HttpTransport.java:73)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
        at org.chromium.components.variations.firstrun.VariationsSeedFetcher.downloadContent(VariationsSeedFetcher.java:231)
        at org.chromium.components.variations.firstrun.VariationsSeedFetcher.fetchSeed(VariationsSeedFetcher.java:171)
        at org.chromium.chrome.browser.init.AsyncInitTaskRunner$FetchSeedTask.doInBackground(AsyncInitTaskRunner.java:53)
        at org.chromium.chrome.browser.init.AsyncInitTaskRunner$FetchSeedTask.doInBackground(AsyncInitTaskRunner.java:40)
        at org.chromium.base.task.AsyncTask$1.call(AsyncTask.java:104)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by kuoruan** [comment]
Did you try our build apk? Crash or not?

**Comment by anhducanh14** [comment]
When i open application not crash just show a dialog "Chrome failed during startup with an unexpected error" and when i click OK is quit

**Comment by kuoruan** [comment]
https://github.com/kuoruan/Chromium-Android/releases/download/v73.0.3683.93/Chromium.apk

**Comment by anhducanh14** [comment]
it error like above ..  i find error in 
![image](https://user-images.githubusercontent.com/14833940/55301498-f3e83b80-540a-11e9-8f3a-99d138de8481.png)

**Comment by anhducanh14** [comment]
error like above but i find error in 
![Screenshot from 2019-03-31 23-16-49](https://user-images.githubusercontent.com/14833940/55301553-44f82f80-540b-11e9-9056-a68dd02cac66.png)

**Comment by anhducanh14** [comment]
did you build libchrome.so again ??

**Comment by kuoruan** [comment]
Everything works well on my device. So I can't reproduce the error.

**Comment by umerkakar** [comment]
Your built app not working on KitKat 4.4.4
Unfortunately chromium has stpped

**Comment by mohamedebrahim96** [comment]
@kuoruan  did you try to test it on android < 21

**Comment by kuoruan** [comment]
I do not have a device with API level < 21, so I can't test it.

**Comment by anhducanh14** [comment]
How i can get webview (build from chromium ) . Tks

**Comment by inCREPAS** [comment]
When i open application show a dialog "Chrome failed during startup with an unexpected error" and when i click OK is quit

**Comment by inCREPAS** [comment]
![error](https://user-images.githubusercontent.com/4309885/60768727-7e26f680-a102-11e9-96f9-67f05e55f169.PNG)
