### ISSUE TITLE
Error when running on KitKat v.4.4.4

### ISSUE THREAD

**Issue by rizkyramadhan** [kuoruan/Chromium-Android#7]
Hi, great project,

Chromium is crashed when I try to deploy it to my device: 

```

03-14 11:58:10.848 31210-31210/? E/AndroidRuntime: FATAL EXCEPTION: main

Process: org.chromium.chrome, PID: 31210
java.lang.RuntimeException: Unable to get provider org.chromium.chrome.browser.util.ChromeFileProvider: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.util.ChromeFileProvider" on path: DexPathList[[zip file "/data/app/org.chromium.chrome-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.chromium.chrome-2, /vendor/lib, /system/lib]]
    at android.app.ActivityThread.installProvider(ActivityThread.java:5246)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4817)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4750)
    at android.app.ActivityThread.access$1500(ActivityThread.java:169)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1573)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5529)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:657)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.util.ChromeFileProvider" on path: DexPathList[[zip file "/data/app/org.chromium.chrome-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.chromium.chrome-2, /vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
    at android.app.ActivityThread.installProvider(ActivityThread.java:5231)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4817) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4750) 
    at android.app.ActivityThread.access$1500(ActivityThread.java:169) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1573) 
    at android.os.Handler.dispatchMessage(Handler.java:110) 
    at android.os.Looper.loop(Looper.java:193) 
    at android.app.ActivityThread.main(ActivityThread.java:5529) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:515) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:657) 
    at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by kuoruan** [comment]
It seams a file is missing. please wait a moment. I will handle it.

**Comment by rizkyramadhan** [comment]
Wow, super fast response. 

Just found this project while compiling chromium to android. I hope this can replace cordova for my project. 

Do you have any success with converting contentshell into android studio ? What kind of problem did you had ?

**Comment by kuoruan** [comment]
I have the plan to convert content shell, maybe some time later.

**Comment by kuoruan** [comment]
Maybe it is caused by ``
`multiDexEnabled true```
https://developer.android.com/studio/build/multidex.html
But I can't find a way to deal it.

**Comment by kuoruan** [comment]
Finally, I find the reason.
My build is ```chrome_modern_public_apk```. It is not support Android API level < 21.
https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md

**Comment by rizkyramadhan** [comment]
Ah, yeah, I suspect that too. Do you plan to replace it with `chrome_public_apk` ?

**Comment by kuoruan** [comment]
Is there any reason that we should support API level < 21? The purpose of this project is to review chromium source code.

**Comment by rizkyramadhan** [comment]
Well, i do have different purpose, maybe i'll fork instead... thanks btw, sorry for this silly problem ..

**Comment by kuoruan** [comment]
If you insist. I will build with ```chrome_public_apk``` in chromium 65.

**Comment by rizkyramadhan** [comment]
haha, don't worry. I'm okay with building my self (I know the way already), you can help me if you try to convert contentshell faster :)

**Comment by nickcartery** [comment]
The same issue :( How to solve it my friends?

**Comment by kuoruan** [comment]
@nickcartery Error log?

**Comment by nickcartery** [comment]
@kuoruan Like the @rizkyramadhan 's post

> java.lang.RuntimeException: Unable to get provider org.chromium.chrome.browser.util.ChromeFileProvider: java.lang.ClassNotFoundException: Didn't find class "org.chromium.chrome.browser.util.ChromeFileProvider" on path: DexPathList[[zip file "/data/app/org.chromium.chrome-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.chromium.chrome-2, /vendor/lib, /system/lib]]

**Comment by nickcartery** [comment]
Most of my users is using android 4.4.2, so this is a big issue :(

**Comment by nickcartery** [comment]
:D Just try and got new error 

> 05-08 17:35:04.177 2367-2367/org.chromium.chrome E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method org.chromium.ui.widget.ButtonCompat.updateButtonBackgroundL


Same with this issue:
https://github.com/JackyAndroid/AndroidChromium/issues/48

**Comment by nickcartery** [comment]
> 05-08 17:39:56.567 2441-2441/org.chromium.chrome E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method org.chromium.base.ApiCompatibilityUtils.setTaskDescription

**Comment by nickcartery** [comment]
The Chromium.apk is created by you which also crashed in Android 4.4.2 (Nox Player emulator)

**Comment by kuoruan** [comment]
```
Could not find class 'android.graphics.drawable.RippleDrawable'
```
This is not a issue. Somewhere else crashes the app. Wait for anyone else to solve this.
